"""empty message

Revision ID: 65381b8249b2
Revises: f8196781d1cb
Create Date: 2022-03-10 15:13:18.679520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65381b8249b2'
down_revision = 'f8196781d1cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gym_table', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gym_table', 'phone')
    # ### end Alembic commands ###
