"""empty message

Revision ID: 7224a5793a49
Revises: 
Create Date: 2022-03-08 12:48:23.738015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7224a5793a49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_table')
    # ### end Alembic commands ###
