"""empty message

Revision ID: 8c384f4ca2d8
Revises: 1ad75ab16380
Create Date: 2022-03-18 15:58:29.642696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c384f4ca2d8'
down_revision = '1ad75ab16380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swiper', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['swiper'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_table')
    # ### end Alembic commands ###
