"""empty message

Revision ID: de117b55a9e5
Revises: 8c384f4ca2d8
Create Date: 2022-03-18 16:00:41.522224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de117b55a9e5'
down_revision = '8c384f4ca2d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_table', sa.Column('swipee', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'match_table', 'user_table', ['swipee'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match_table', type_='foreignkey')
    op.drop_column('match_table', 'swipee')
    # ### end Alembic commands ###
