"""empty message

Revision ID: f8196781d1cb
Revises: 7224a5793a49
Create Date: 2022-03-10 08:59:34.954922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8196781d1cb'
down_revision = '7224a5793a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_table', sa.Column('boulder_max_grade', sa.String(), nullable=True))
    op.add_column('user_table', sa.Column('boulder_reg_grade', sa.String(), nullable=True))
    op.add_column('user_table', sa.Column('top_max_grade', sa.String(), nullable=True))
    op.add_column('user_table', sa.Column('top_reg_grade', sa.String(), nullable=True))
    op.add_column('user_table', sa.Column('lead_max_grade', sa.String(), nullable=True))
    op.add_column('user_table', sa.Column('lead_reg_grade', sa.String(), nullable=True))
    op.add_column('user_table', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('user_table', sa.Column('city', sa.String(), nullable=True))
    op.add_column('user_table', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'state')
    op.drop_column('user_table', 'city')
    op.drop_column('user_table', 'bio')
    op.drop_column('user_table', 'lead_reg_grade')
    op.drop_column('user_table', 'lead_max_grade')
    op.drop_column('user_table', 'top_reg_grade')
    op.drop_column('user_table', 'top_max_grade')
    op.drop_column('user_table', 'boulder_reg_grade')
    op.drop_column('user_table', 'boulder_max_grade')
    op.drop_table('gym_table')
    # ### end Alembic commands ###
